services:
  postgres:
    image: postgres:16
    container_name: aquaventure-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aquaventure_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@123
    ports:
      - "5432:5432"
    volumes:
      - aquaventure_pgdata:/var/lib/postgresql/data

volumes:
  aquaventure_pgdata:
