spring.application.name=aquaventure
spring.datasource.url=jdbc:postgresql://localhost:5432/aquaventure_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.error.include-message=always
jwt.secret=aquaventure_super_secret_key_2026_change_this_in_prod_32bytes

server.port=8080